name: lvs

on:
  push:
  workflow_dispatch:

jobs:
  lvs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up environment variables
        shell: bash
        run: |
          cat << EOF >> $GITHUB_ENV
          PDK_ROOT=/home/runner/pdk
          PDK=sky130A
          MAGIC_VERSION=master
          NETGEN_VERSION=master
          EOF
  
      - name: Install Sky130 PDK
        uses: TinyTapeout/volare-action@v1
        with:
          pdk_name: sky130
          pdk_version: 78b7bc32ddb4b6f14f76883c2e2dc5b5de9d1cbc
          pdk_root: /home/runner/pdk

      - name: Magic
        shell: bash
        run: |
            sudo apt-get install -y m4 python3 libx11-dev tcl-dev tk-dev libcairo2-dev mesa-common-dev libglu1-mesa-dev
            git clone -b $MAGIC_VERSION https://github.com/RTimothyEdwards/magic /tmp/magic
            cd /tmp/magic
            ./configure
            make -j4 
            sudo make install

      - name: Netgen
        shell: bash
        run: |
            git clone -b $NETGEN_VERSION https://github.com/RTimothyEdwards/netgen /tmp/netgen
            cd /tmp/netgen
            ./configure
            make -j4 
            sudo make install

      - name: Run LVS
        shell: bash
        run: |
            cd mag
            make lvs
